In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
# read data from explorer, 
filepath = "C:/Users/WALDMJN/OneDrive - Schaeffler/Uni/Data Exploration Project/Pred Maintenance Project/Predictive-Maintenance/Data/predictive_maintenance.csv"
df = pd.read_csv(filepath)
df.sample(10)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
3271,3272,M18131,M,301.4,310.0,1689,32.1,207,0,No Failure
3381,3382,L50561,L,301.3,310.6,1376,47.6,45,0,No Failure
7078,7079,L54258,L,300.7,310.5,1357,52.6,199,0,No Failure
683,684,L47863,L,297.7,309.0,1874,24.4,28,0,No Failure
9975,9976,M24835,M,298.6,308.3,1589,34.1,174,0,No Failure
1908,1909,L49088,L,297.9,307.6,1977,20.2,182,0,No Failure
5990,5991,M20850,M,300.7,310.7,1343,51.6,211,0,No Failure
1173,1174,H30587,H,297.1,308.0,1559,38.8,229,0,No Failure
4254,4255,L51434,L,302.6,311.0,1284,68.0,114,1,Power Failure
5030,5031,M19890,M,303.9,313.1,1437,48.3,110,0,No Failure

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Target                   10000 non-null  int64
 9   Failure Type             10000 non-null  object
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB